# -*- coding: utf-8 -*-
"""to do list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mP485FCDt_Sl2xYbxR6OtRqDVl1PdRIp
"""

class ToDoList:
    def __init__(self):
        self.tasks = []

    # add a task
    def add_task(self, task_id, task_name):
        for task in self.tasks:
            if task['id'] == task_id:
                print(f"Task with id {task_id} already exists.")
                return
        # If task id does not exist, append a new task
        self.tasks.append({"id": task_id, "name": task_name})
        print(f"Task '{task_name}' added successfully.")

    #  edit an existing task
    def edit_task(self, task_id, new_task_name):
        for task in self.tasks:
            if task['id'] == task_id:
                task['name'] = new_task_name
                print(f"Task with id {task_id} updated to '{new_task_name}'.")
                return
        print(f"No task found with id {task_id}.")

    # delete a task by its id
    def delete_task(self, task_id):
        for task in self.tasks:
            if task['id'] == task_id:
                self.tasks.remove(task)
                print(f"Task with id {task_id} deleted.")
                return
        print(f"No task found with id {task_id}.")

    # print all tasks
    def print_tasks(self):
        if not self.tasks:
            print("No tasks in the list.")
        else:
            print("To-Do List:")
            for task in self.tasks:
                print(f"Task ID: {task['id']}, Task Name: {task['name']}")

todo = ToDoList()

# Adding tasks
todo.add_task(1, "Hey I am first task")
todo.add_task(2, "This is the second task")

# Editing a task
todo.edit_task(1, "Updated first task")

# Deleting a task
todo.delete_task(2)

# Printing all tasks
todo.print_tasks()

